version: '3'
services:
  database:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'ebanx-test'
  app:
    build: .
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
    command: sh -c "yarn && yarn start:dev"
    depends_on:
      - database

